### ISSUE TITLE
Postgres role loads data into `postgres` database

### ISSUE THREAD

**Issue by lenards** [iPlantCollaborativeOpenSource/clank#29]
Right now, the task that uses `psql` just uses `-f` without indicating the target database. This means the default database for the user is the target (and, for `postgres` user that is `postgres` database). 

```yaml
- name: run troposphere sql script for postgresql
  become: yes
  become_user: postgres
  command: psql -f {{ POSTGRES_SQL_INSTALL_DIRECTORY }}/{{ TROPOSPHERE_DATABASE_FILE_TO_BE_LOADED | basename }}
  when: LOAD_TROPOSPHERE_DATABASE
  register: output
```
source: [troposphere-setup-troposphere/tasks/main.yml](https://github.com/iPlantCollaborativeOpenSource/clank/blob/db1f6d57fdb7a03a1a7607c8b38c9a91bfeb8349/roles/troposphere-setup-troposphere/tasks/main.yml#L69-L74)

:information_source: This will be corrected in a **forthcoming** pull request that I am authoring.
