### ISSUE TITLE
Under Ansible 2.1, role/clone-repo fails`

### ISSUE THREAD

**Issue by lenards** [iPlantCollaborativeOpenSource/clank#52]
This currently works under Ansible 2.0.1.0 and breaks when updated to 2.1

## Output Snippet 

This is a snippet from `playbooks/deploy_troposphere.yml`

```
TASK [setup-virtualenv : debug] ************************************************
skipping: [localhost]

TASK [clone-repo : debug] ******************************************************
ok: [localhost] => {
    "CLONE_TARGET": null
}

TASK [clone-repo : clone git repo with branched defined] ***********************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "the destination directory must be specified unless clone=no"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/vagrant/scratch/clank/playbooks/test-one-off.retry

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   
```

The odd thing is that `TROPOSPHERE_LOCATION` is passed to the role as `CLONE_TARGET`:
```yaml
  roles:
    - { role: setup-virtualenv,
        VIRTUAL_ENV_NAME: 'troposphere',
        VIRTUAL_ENV_BASE_DIR: "{{ VIRTUAL_ENV_DIR_TROPOSPHERE }}",
        tags: [ 'troposphere', 'setup-virtualenv'] }

    - { role: clone-repo,
        REPO_BASE_DIR: "{{ TROPOSPHERE_DIR }}",
        CLONE_TARGET: "{{ TROPOSPHERE_LOCATION }}",
        SPECIFIC_BRANCH: "{{ TROPOSPHERE_BRANCH | default('master', true) }}",
        REPO_URI: "{{ TROPOSPHERE_REPO }}",
        tags: [ 'troposphere', 'clone-repo'] }
```

Have the semantics for parameterizing roles changed from Ansible 2.0 to 2.1?
