### ISSUE TITLE
Issues with clank install

### ISSUE THREAD

**Issue by lokI8** [iPlantCollaborativeOpenSource/clank#63]
Hello all,

I'm installing atmosphere using clank in a 16.04 Ubuntu vm, and we've hit a few issues that we thought you guys might want to know about.

The atmosphere repo cloned to /opt/dev/atmosphere has uWSGI version 2.0.9 in it's requirements.txt. We are hitting a compilation error on this package described here: https://github.com/unbit/uwsgi/issues/1262. We've tried changing the version number to 2.0.13, but then clank won't let us pass the cloning of the atmosphere repo, as we've made modifications and it can't pull. We're trying on an older version of Ubuntu now.

Two more issues you guys might want to know about:
1) We had to hard code the version number of postgresql to 9.5 in the main.yml of setup-postgres/tasks, as changing the variable in any of the files in var did not propagate to the ansible role, and the version of postgres automatically installed from clank was 9.5.
2) We had to manually install ruby 1.9.1 and comment out the line in the requirements file. There is no package matching that exact name on this version of Ubuntu, and apt-get does a reg-ex match to install the correct packages, so when the installer was unable to find it, it error'd out.

**Comment by xuhang57** [comment]
Adding to that, Jon and I tried to switch from Ubuntu 16.04 to 14.04 LTS and we passed those above errors. During the installation, we add a global variable in `dist_files\variables.yml` to fix an error that `TASK [app-generate-ini-config : create local variables.ini.ini from dict] ******
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'MOCK_USERNAME' is undefined"}``

However after that, we failed at the stage **: TASK [app-generate-ini-config : run generate script for app] *********************

The specific errors we are getting are
 `Undeclared variables found in /opt/dev/atmosphere/extras/init.d/celeryd.default.dist.j2: \n\t- FLOWER_EMAIL_ACCESS_LIST\n\t- FLOWER_OAUTH2_REDIRECT_URI\n\t- FLOWER_OAUTH2_CLIENT_ID\n\t- FLOWER_AUTH_SCHEME\n\t- FLOWER_BASIC_PASSWORD\n\t- FLOWER_OAUTH2_CLIENT_SECRET\n\t- FLOWER_BASIC_USERNAME` 

And some other errors like `Unused variables found in section local.py` on auth parameters even though we set MOC_AUTH as True in the `variables.yml` file. 

Apologize for throwing so many installation errors at one time. It would be much appreciated if any of you can point us the direction of fix them. Thanks for your help!

**Comment by lenards** [comment]
@xuhang57 @lokI8 - I can get you basic values for the `FLOWER_*` variables - that lacking from dist_files/variables.yml is an oversight.

**Comment by lenards** [comment]
@xuhang57 no apologies necessary - thank you for providing details for us.

**Comment by lenards** [comment]
@lokI8 & @xuhang57 

```
ATMO:
    # .... 
    celeryd.default:
        # ... 
        FLOWER_AUTH_SCHEME: "basic"
        # Required if auth_scheme is 'basic'
        FLOWER_BASIC_USERNAME: "<username-redacted>"
        FLOWER_BASIC_PASSWORD: "<password-redacted>"
        # Required if auth_scheme is 'google' 
        FLOWER_EMAIL_ACCESS_LIST:
        FLOWER_OAUTH2_CLIENT_ID:
        FLOWER_OAUTH2_CLIENT_SECRET:
        FLOWER_OAUTH2_REDIRECT_URI:
```
