### ISSUE TITLE
Creation of self-signed crt and combined leads to nginx errors

### ISSUE THREAD

**Issue by steve-gregory** [iPlantCollaborativeOpenSource/clank#79]
The error being reported:
`6571#6571: SSL_CTX_use_PrivateKey_file("/etc/ssl/private//self-signed.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)`

The state of the file system:
```
root:~# ll /etc/ssl/private/se*
-rw-r--r-- 1 root root 1704 Jun 28 20:36 /etc/ssl/private/self-signed.key
root:~# ll /etc/ssl/certs/se*
-rw-r--r-- 1 root root 1350 Jun 28 20:35 /etc/ssl/certs/self_signed_combined.crt
-rw-r--r-- 1 root root 1350 Jun 28 20:36 /etc/ssl/certs/self-signed.crt
```
What was required to fix it:
```
cp /etc/ssl/certs/self-signed.crt /etc/ssl/certs/self_signed_combined.crt
```

**Comment by lenards** [comment]
Confirmed in vagrant environment.

**Comment by lenards** [comment]
You can also do:
```bash
rm /etc/ssl/certs/self_signed_combined.crt
cd /opt/dev/troposphere/extras/nginx
make /etc/ssl/certs/self_signed_combined.crt
```

**Comment by lenards** [comment]
This also affects celery & flower ..

**Comment by lenards** [comment]
I mentioned #73 because when you leave the following blank: 

```yaml
SSL_CERTIFICATE:    #Absolute Path Recommended
BUNDLE_CERT:        #Absolute Path Recommended
SSL_KEY:            #Absolute Path Recommended
```

These blank values will be used in `ATMO['celeryd.default']`. This seems to be one likely cause of the above message.
